---
title: Isabelinaz.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Isabelle Z
description: Spreading Love&Hapiness
avatar: https://avatars2.githubusercontent.com/u/32156315
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: ZarateIsabelina
  stackoverflow: 
  youtube: 
  googleplus: u/0/105107242703964370717
disqus: disqus_GWGlktwFj9
google_analytics: 
url: https://isabelinaz.github.io/
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
